[build]
  # Custom build command to install Go and then build Gatsby
  command = "bash install_go.sh && gatsby build"
  publish = "public"  # The output directory for Gatsby build

[[plugins]]
  package = "@netlify/plugin-gatsby"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = true
